# automatically build docker images for all microservices when push on main branch

DOCKER_USERNAME=
DOCKER_PASSWORD=

name: Build and Push Docker Images
on:
  push:
    branches:
      - main
    
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ammar266
          password: leftiesrule000

      - name: Build and push Docker images
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 --push -t ammar266/microservice1:latest ./api-gateway
          docker buildx build --platform linux/amd64,linux/arm64 --push -t ammar266/microservice2:latest ./customer-services
          docker buildx build --platform linux/amd64,linux/arm64 --push -t ammar266/microservice3:latest ./inventory-services
          docker buildx build --platform linux/amd64,linux/arm64 --push -t ammar266/microservice4:latest ./menu-services
          docker buildx build --platform linux/amd64,linux/arm64 --push -t ammar266/microservice5:latest ./order-services
          docker buildx build --platform linux/amd64,linux/arm64 --push -t ammar266/microservice6:latest ./payment-services